# Generated by Django 2.2 on 2019-04-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat', models.CharField(max_length=250)),
                ('severity', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('attacker', models.CharField(max_length=16, null=True)),
                ('target', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
