# Generated by Django 2.2 on 2019-04-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='attacker',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='target',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='threat',
        ),
        migrations.AddField(
            model_name='alerts',
            name='destination',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='alerts',
            name='incident_type',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerts',
            name='is_threat',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='alerts',
            name='rule',
            field=models.CharField(default='aa', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerts',
            name='source',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='alerts',
            name='tool_alias',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='severity',
            field=models.CharField(max_length=2),
        ),
    ]
