# Generated by Django 2.2 on 2019-04-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0002_auto_20190407_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='destination',
            new_name='detection_ip',
        ),
    ]
