# Generated by Django 2.2 on 2019-04-10 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0003_auto_20190410_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='detection_ip',
            new_name='destination',
        ),
    ]
