# Generated by Django 2.2 on 2019-04-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0004_auto_20190410_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
