# Generated by Django 2.2 on 2019-04-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0005_alerts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
