# Generated by Django 2.2 on 2019-04-13 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0007_alerts_alert_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='rule',
            new_name='rule_name',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='alert_id',
        ),
    ]
