# Generated by Django 2.2 on 2019-04-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0009_auto_20190416_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='is_threat',
        ),
    ]
