# Generated by Django 2.2 on 2019-04-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0012_auto_20190423_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='destination',
            field=models.CharField(blank=True, default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='manager',
            field=models.CharField(blank=True, default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='source',
            field=models.CharField(blank=True, default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=100),
        ),
    ]
