# Generated by Django 2.2 on 2019-04-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0014_auto_20190423_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertSettings',
        ),
        migrations.RemoveField(
            model_name='timerules',
            name='def_time',
        ),
        migrations.AddField(
            model_name='timerules',
            name='status',
            field=models.CharField(default='Disabled', max_length=15),
        ),
        migrations.AlterField(
            model_name='timerules',
            name='severity',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='timerules',
            name='time',
            field=models.CharField(blank=True, default='', max_length=19),
        ),
    ]
