# Generated by Django 2.2 on 2019-04-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0015_auto_20190423_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='analyst_note',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='is_threat',
            field=models.CharField(blank=True, default='Unknown', max_length=7),
        ),
    ]
