# Generated by Django 2.2 on 2019-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0017_auto_20190429_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='false',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=500)),
                ('incident_type', models.CharField(max_length=100)),
                ('tool_alias', models.CharField(blank=True, default='Unknown', max_length=500)),
                ('date', models.CharField(max_length=19)),
                ('severity', models.CharField(max_length=2)),
                ('source', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('destination', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('is_threat', models.CharField(blank=True, default='Unknown', max_length=7)),
                ('manager', models.CharField(blank=True, default='Pending...', max_length=100)),
                ('status', models.CharField(default='False Positive', max_length=15)),
            ],
        ),
    ]
