# Generated by Django 2.2 on 2019-04-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0018_false'),
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=500)),
                ('type', models.CharField(default='Default', max_length=100)),
                ('schedule', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=19)),
                ('next_date', models.CharField(default='', max_length=19)),
                ('owner', models.CharField(default='System', max_length=100)),
                ('view', models.CharField(default='HTML', max_length=50)),
            ],
        ),
    ]
