# Generated by Django 2.2 on 2019-04-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0019_reports'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reports',
            new_name='report',
        ),
    ]
