# Generated by Django 2.2 on 2019-04-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0020_auto_20190430_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerules',
            name='autoincr',
            field=models.CharField(default='FALSE', max_length=5),
        ),
    ]
