# Generated by Django 2.2 on 2019-05-01 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0021_timerules_autoincr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='next_date',
            new_name='next_run_time',
        ),
    ]
