# Generated by Django 2.2 on 2019-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0022_auto_20190501_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_monitoring',
            fields=[
                ('severity', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=19)),
                ('auto_notify', models.CharField(default='DISABLED', max_length=8)),
            ],
        ),
    ]
