# Generated by Django 2.2 on 2019-05-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0023_ticket_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_monitoring',
            name='notify_time',
            field=models.CharField(default='1', max_length=4),
        ),
    ]
