# Generated by Django 2.2 on 2019-05-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0025_alerts_s_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='s_updated',
        ),
    ]
