# Generated by Django 2.2 on 2019-05-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0026_remove_alerts_s_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='open_ticket',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('time', models.DecimalField(decimal_places=10, max_digits=19)),
                ('current', models.DecimalField(decimal_places=10, max_digits=19)),
                ('half', models.DecimalField(decimal_places=10, max_digits=19)),
                ('auto', models.CharField(max_length=5)),
                ('expiring', models.DecimalField(decimal_places=10, max_digits=19)),
                ('rt', models.CharField(default='0', max_length=1)),
                ('expired', models.CharField(default='0', max_length=1)),
                ('manager', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket_monitoring',
            name='notify_time',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ticket_monitoring',
            name='time',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
