# Generated by Django 2.2 on 2019-05-06 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0028_auto_20190506_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='open_ticket',
            name='rt',
        ),
    ]
