# Generated by Django 2.2 on 2019-05-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0029_remove_open_ticket_rt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_ticket',
            name='current',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='open_ticket',
            name='expiring',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='open_ticket',
            name='half',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='open_ticket',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='open_ticket',
            name='time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ticket_monitoring',
            name='notify_time',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='ticket_monitoring',
            name='time',
            field=models.FloatField(),
        ),
    ]
