# Generated by Django 2.2 on 2019-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0030_auto_20190507_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_ticket',
            name='auto',
            field=models.CharField(max_length=6),
        ),
    ]
