# Generated by Django 2.2 on 2019-05-07 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0031_auto_20190507_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='generate_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=500)),
                ('type', models.CharField(default='Default', max_length=100)),
                ('schedule', models.CharField(max_length=50)),
                ('creation_date', models.CharField(max_length=19)),
                ('next_run_time', models.CharField(default='None', max_length=19)),
                ('owner', models.CharField(default='System', max_length=100)),
                ('view', models.CharField(default='HTML', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='next_run_time',
        ),
        migrations.RemoveField(
            model_name='report',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='report',
            name='type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='view',
        ),
        migrations.AddField(
            model_name='report',
            name='instance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Alfaros.generate_report'),
            preserve_default=False,
        ),
    ]
