# Generated by Django 2.2 on 2019-05-07 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0032_auto_20190507_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='instance',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='Alfaros.generate_report'),
        ),
    ]
