# Generated by Django 2.2 on 2019-05-07 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0033_auto_20190507_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Alfaros.generate_report'),
        ),
    ]
