# Generated by Django 2.2 on 2019-05-07 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0036_auto_20190508_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='generate_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=500)),
                ('type', models.CharField(default='Default', max_length=100)),
                ('schedule', models.CharField(max_length=50)),
                ('creation_date', models.CharField(max_length=19)),
                ('next_run_time', models.CharField(default='', max_length=19)),
                ('owner', models.CharField(default='System', max_length=100)),
                ('view', models.CharField(default='HTML', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='other',
            field=models.ForeignKey(default='Changed', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Alfaros.generate_report'),
        ),
    ]
