# Generated by Django 2.2 on 2019-05-07 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0037_auto_20190508_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='other',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Alfaros.generate_report'),
        ),
    ]
