# Generated by Django 2.2 on 2019-05-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0040_auto_20190508_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='other',
        ),
    ]
