# Generated by Django 2.2 on 2019-05-08 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0041_remove_report_other'),
    ]

    operations = [
        migrations.DeleteModel(
            name='generate_report',
        ),
    ]
