# Generated by Django 2.2 on 2019-05-08 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0042_delete_generate_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alerts',
        ),
        migrations.DeleteModel(
            name='false',
        ),
        migrations.DeleteModel(
            name='open_ticket',
        ),
        migrations.DeleteModel(
            name='report',
        ),
        migrations.DeleteModel(
            name='ticket_monitoring',
        ),
        migrations.DeleteModel(
            name='TimeRules',
        ),
    ]
