# Generated by Django 2.2 on 2019-05-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0044_alerts_false_open_ticket_report_ticket_monitoring_timerules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='report',
        ),
    ]
