# Generated by Django 2.2 on 2019-05-08 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0045_delete_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alerts',
        ),
        migrations.DeleteModel(
            name='false',
        ),
        migrations.DeleteModel(
            name='open_ticket',
        ),
        migrations.DeleteModel(
            name='ticket_monitoring',
        ),
        migrations.DeleteModel(
            name='TimeRules',
        ),
    ]
