# Generated by Django 2.2 on 2019-05-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alfaros', '0046_auto_20190508_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=500)),
                ('incident_type', models.CharField(max_length=100)),
                ('tool_alias', models.CharField(blank=True, default='Unknown', max_length=500)),
                ('date', models.CharField(max_length=19)),
                ('severity', models.CharField(max_length=2)),
                ('source', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('destination', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('is_threat', models.CharField(blank=True, default='Unknown', max_length=7)),
                ('manager', models.CharField(blank=True, default='Pending...', max_length=100)),
                ('status', models.CharField(blank=True, default='Pending...', max_length=100)),
                ('analyst_note', models.CharField(blank=True, default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='false',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=500)),
                ('incident_type', models.CharField(max_length=100)),
                ('tool_alias', models.CharField(blank=True, default='Unknown', max_length=500)),
                ('date', models.CharField(max_length=19)),
                ('severity', models.CharField(max_length=2)),
                ('source', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('destination', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('is_threat', models.CharField(blank=True, default='Unknown', max_length=7)),
                ('manager', models.CharField(blank=True, default='Pending...', max_length=100)),
                ('status', models.CharField(default='False Positive', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='open_ticket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.FloatField()),
                ('current', models.FloatField()),
                ('half', models.FloatField()),
                ('auto', models.CharField(max_length=6)),
                ('expiring', models.FloatField()),
                ('expired', models.CharField(default='0', max_length=1)),
                ('manager', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=500)),
                ('type', models.CharField(default='Default', max_length=100)),
                ('schedule', models.CharField(max_length=50)),
                ('creation_date', models.CharField(max_length=19)),
                ('next_run_time', models.CharField(default='', max_length=19)),
                ('owner', models.CharField(default='System', max_length=100)),
                ('view', models.CharField(default='HTML', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ticket_monitoring',
            fields=[
                ('severity', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('time', models.FloatField()),
                ('auto_notify', models.CharField(default='DISABLED', max_length=8)),
                ('notify_time', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRules',
            fields=[
                ('rule_name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('time', models.CharField(blank=True, default='', max_length=19)),
                ('autoincr', models.CharField(default='FALSE', max_length=5)),
                ('severity', models.CharField(blank=True, default='', max_length=2)),
                ('status', models.CharField(default='Disabled', max_length=15)),
            ],
        ),
    ]
