# Generated by Django 2.2 on 2019-05-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0047_alerts_false_open_ticket_report_ticket_monitoring_timerules'),
    ]

    operations = [
        migrations.CreateModel(
            name='generate_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=500)),
                ('type', models.CharField(default='Default', max_length=100)),
                ('schedule', models.CharField(max_length=50)),
                ('creation_date', models.CharField(max_length=19)),
                ('next_run_time', models.CharField(default='', max_length=19)),
                ('owner', models.CharField(default='System', max_length=100)),
                ('view', models.CharField(default='HTML', max_length=50)),
            ],
        ),
    ]
