# Generated by Django 2.2 on 2019-05-08 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0048_generate_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Alfaros.generate_report'),
        ),
    ]
