# Generated by Django 2.2 on 2019-05-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0049_report_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ref',
        ),
        migrations.AddField(
            model_name='generate_report',
            name='search',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generate_report',
            name='next_run_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='next_run_time',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='report',
            name='owner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='view',
            field=models.CharField(max_length=50),
        ),
    ]
