# Generated by Django 2.2 on 2019-05-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0050_auto_20190508_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerules',
            name='severity',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='timerules',
            name='time',
            field=models.CharField(default='', max_length=19),
        ),
    ]
