# Generated by Django 2.2 on 2019-05-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alfaros', '0051_auto_20190510_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerules',
            name='severity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='timerules',
            name='time',
            field=models.FloatField(),
        ),
    ]
